Repository dotnet/docs.zh-cn, pull requests merged in 2018-02, with the labels that each got.

#101 Update best-practices.md
  docs/standard/base-types/best-practices.md
Labels: In Progress, Linguistic Suggestion

#110 fix #62
  docs/csharp/programming-guide/classes-and-structs/polymorphism.md
Labels: Accepted, Linguistic Suggestion

#108 replace "放弃" with "空占位符"
  docs/csharp/discards.md
Labels: Accepted, Linguistic Suggestion, MS FTE Contributor

#111 Update how-to-find-controltemplate-generated-elements.md
  docs/framework/wpf/controls/how-to-find-controltemplate-generated-elements.md
Labels: In Progress, Linguistic Suggestion

#113 Update regular-expressions.md
  docs/standard/base-types/regular-expressions.md
Labels: Accepted, Linguistic Suggestion
