Repository dotnet/docs.zh-cn, pull requests merged in 2018-12, with the labels that each got.

#275 培训->训练
  docs/machine-learning/resources/glossary.md
Labels: In Progress, Linguistic Suggestion

#281 ： -> -
  docs/csharp/language-reference/operators/index.md
Labels: Accepted, Linguistic Suggestion

#269 Update docker-containers-images-and-registries.md
  docs/standard/containerized-lifecycle-architecture/docker-containers-images-and-registries.md
Labels: Accepted, Linguistic Suggestion

#257 No need to translate "new"
  docs/standard/modern-web-apps-azure-architecture/develop-asp-net-core-mvc-apps.md
Labels: Accepted, Linguistic Suggestion

#262 修正翻译
  docs/standard/library-guidance/sourcelink.md
Labels: Accepted, Linguistic Suggestion

#263 修正翻译
  docs/standard/library-guidance/breaking-changes.md
Labels: Accepted, Linguistic Suggestion

#246 Translate OS
  docs/standard/components.md
Labels: Accepted, Linguistic Suggestion

#258 修正翻译
  docs/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps.md
Labels: Accepted, Linguistic Suggestion

#259 修正翻译
  docs/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps.md
Labels: Accepted, Linguistic Suggestion

#283 建议->推荐
  docs/machine-learning/resources/tasks.md
Labels: Accepted, Linguistic Suggestion

#290 Keep original keywords
  docs/csharp/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#287 Update names-of-type-members.md
  docs/standard/design-guidelines/names-of-type-members.md
Labels: Accepted, Linguistic Suggestion

#284 Create dotnet-core-2-2.md
  docs/core/whats-new/dotnet-core-2-2.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#303 Update events-and-callbacks.md
  docs/standard/design-guidelines/events-and-callbacks.md
Labels: Accepted, Linguistic Suggestion

#302 Update protected-members.md
  docs/standard/design-guidelines/protected-members.md
Labels: Accepted, Linguistic Suggestion

#265 Update what-is-docker.md
  docs/standard/containerized-lifecycle-architecture/what-is-docker.md
Labels: Accepted, Linguistic Suggestion

#301 Fix translations
  docs/standard/base-types/grouping-constructs-in-regular-expressions.md
Labels: Accepted

#299 元祖 -> 元组
  docs/csharp/lambda-expressions.md
  docs/visual-basic/getting-started/whats-new.md
Labels: Accepted, Linguistic Suggestion

#288 Update index.md
  docs/framework/debug-trace-profile/index.md
Labels: Accepted, Linguistic Suggestion

#286 Update general-naming-conventions.md
  docs/standard/design-guidelines/general-naming-conventions.md
Labels: Accepted, Linguistic Suggestion
