Repository dotnet/docs.zh-cn, pull requests merged in 2018-10, with the labels that each got.

#203 Update async-in-depth.md
  docs/standard/async-in-depth.md
Labels: Accepted, Linguistic Suggestion

#205 Update index.md
  docs/standard/microservices-architecture/container-docker-introduction/index.md
Labels: Accepted, Linguistic Suggestion

#206 Update docker-terminology.md
  docs/standard/microservices-architecture/container-docker-introduction/docker-terminology.md
Labels: Accepted, Linguistic Suggestion

#216 Update choosing-between-class-and-struct.md
  docs/standard/design-guidelines/choosing-between-class-and-struct.md
Labels: In Progress, Linguistic Suggestion

#221 Update net-standard-table.md
  includes/net-standard-table.md
Labels: Accepted, Source Issue

#223 Update using-delegates.md
  docs/csharp/programming-guide/delegates/using-delegates.md
Labels: Accepted, Linguistic Suggestion

#220 Update docker-containers-images-registries.md
  docs/standard/microservices-architecture/container-docker-introduction/docker-containers-images-registries.md
Labels: Accepted, Linguistic Suggestion

#218 Feedback for member.
  docs/standard/design-guidelines/member.md
Labels: Accepted, Linguistic Suggestion

#225 Feedback
  docs/standard/design-guidelines/type.md
Labels: Accepted, Linguistic Suggestion
