Repository dotnet/docs.zh-cn, pull requests merged in 2019-03, with the labels that each got.

#340 错别字 前景 -> 进行
  docs/standard/garbage-collection/latency.md
Labels: Linguistic Suggestion, Partially Accepted

#341 Revert keywords translation
  docs/csharp/language-reference/keywords/toc.md
Labels: Accepted, Linguistic Suggestion

#347 Fix：'run out of work' typo error translation
  docs/csharp/programming-guide/concepts/async/index.md
Labels: Linguistic Suggestion

#345 Fix：Make up for the missing translation
  docs/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types.md
Labels: In Progress, Linguistic Suggestion, Partially Accepted

#354 fixed the type error.
  docs/framework/wpf/controls/customizing-the-appearance-of-an-existing-control.md
Labels: Linguistic Suggestion, Partially Accepted

#355 Update tour.md
  docs/fsharp/tour.md
Labels: Linguistic Suggestion, Partially Accepted
