Repository dotnet/docs.zh-cn, pull requests merged in 2019-01, with the labels that each got.

#312 Update what-is-fsharp.md
  docs/fsharp/what-is-fsharp.md
Labels: Accepted, Linguistic Suggestion

#310 重新 -> 重写
  docs/csharp/language-reference/keywords/override.md
Labels: Accepted, Linguistic Suggestion

#309 Update tour.md
  docs/standard/tour.md
Labels: Accepted, Linguistic Suggestion

#314 update wpf data binding translations
  docs/framework/wpf/data/how-to-bind-the-properties-of-two-controls.md
  docs/framework/wpf/data/how-to-bind-to-a-collection-and-display-information-based-on-selection.md
  docs/framework/wpf/data/how-to-bind-to-an-enumeration.md
  docs/framework/wpf/data/how-to-control-when-the-textbox-text-updates-the-source.md
  docs/framework/wpf/data/how-to-convert-bound-data.md
  docs/framework/wpf/data/how-to-create-a-binding-in-code.md
  docs/framework/wpf/data/how-to-get-the-binding-object-from-a-bound-target-property.md
  docs/framework/wpf/data/how-to-get-the-default-view-of-a-data-collection.md
  docs/framework/wpf/data/how-to-implement-a-compositecollection.md
  docs/framework/wpf/data/how-to-implement-binding-validation.md
  docs/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects.md
  docs/framework/wpf/data/how-to-make-data-available-for-binding-in-xaml.md
  docs/framework/wpf/data/how-to-specify-the-binding-source.md
  docs/framework/wpf/data/how-to-specify-the-direction-of-the-binding.md
Labels: Accepted, Linguistic Suggestion

#315 dotnet/fsharp/tour.md
  docs/fsharp/tour.md
Labels: Accepted, Linguistic Suggestion

#297 Fix translations and marks
  docs/standard/base-types/regular-expression-language-quick-reference.md
Labels: Accepted, Linguistic Suggestion, Source Issue, Technical Issue

#316 lymim.doc trans
  docs/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection.md
  docs/framework/wpf/data/how-to-filter-data-in-a-view.md
  docs/framework/wpf/data/how-to-implement-property-change-notification.md
  docs/framework/wpf/data/how-to-navigate-through-the-objects-in-a-data-collectionview.md
  docs/framework/wpf/data/how-to-sort-and-group-data-using-a-view-in-xaml.md
  docs/framework/wpf/data/how-to-sort-data-in-a-view.md
  docs/framework/wpf/data/how-to-use-the-master-detail-pattern-with-hierarchical-data.md
  docs/framework/wpf/data/how-to-use-the-master-detail-pattern-with-hierarchical-xml-data.md
Labels: In Progress, Linguistic Suggestion

#324 Update dotnet-test.md
  docs/core/tools/dotnet-test.md
Labels: Accepted, Linguistic Suggestion

#326 添加标点
  docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md
Labels: In Progress, Linguistic Suggestion

#329 Update system-requirements.md
  docs/framework/get-started/system-requirements.md
Labels: Accepted, Linguistic Suggestion
