Repository dotnet/docs.zh-cn, pull requests merged in 2019-10, with the labels that each got.

#485 Update microservice-domain-model.md
  docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model.md
Labels: Accepted, Linguistic Suggestion

#484 完整堆栈 -> 全栈
  docs/core/index.md
Labels: Accepted, Linguistic Suggestion

#487 Fix backtick issue
  docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md
  docs/core/tools/dotnet-new.md
  docs/csharp/language-reference/keywords/virtual.md
  docs/csharp/language-reference/operators/bitwise-and-shift-operators.md
  docs/csharp/language-reference/operators/pointer-related-operators.md
  docs/csharp/misc/cs0459.md
  docs/csharp/programming-guide/unsafe-code-pointers/pointer-types.md
  docs/framework/debug-trace-profile/marshaling-mda.md
  docs/framework/interop/msgbox-sample.md
  docs/framework/misc/security-transparent-code-level-2.md
  docs/framework/unmanaged-api/debugging/icordebugilcode-getehclauses-method.md
  docs/framework/unmanaged-api/debugging/icordebugilcode2-getinstrumentedilmap-method.md
  docs/framework/unmanaged-api/fusion/compareassemblyidentity-function.md
  docs/framework/wcf/feature-details/how-to-publish-metadata-for-a-service-using-a-configuration-file.md
  docs/framework/wcf/feature-details/how-to-use-the-aspnet-membership-provider.md
  docs/framework/wcf/feature-details/reliable-messaging-protocol-version-1-1.md
  docs/framework/wcf/feature-details/wcf-web-http-service-help-page.md
  docs/framework/winforms/advanced/walkthrough-demonstrating-visual-inheritance.md
  docs/framework/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application.md
  docs/framework/wpf/advanced/dependency-property-value-precedence.md
  docs/framework/wpf/app-development/dialog-boxes-overview.md
  docs/fsharp/language-reference/enumerations.md
  docs/fsharp/language-reference/symbol-and-operator-reference/index.md
  docs/machine-learning/tutorials/movie-recommendation.md
  docs/standard/assembly/unloadability.md
  docs/standard/datetime/enumerate-time-zones.md
  docs/standard/io/file-path-formats.md
  docs/visual-basic/developing-apps/development-with-my/performing-tasks-with-my-application-my-computer-and-my-user.md
  docs/visual-basic/language-reference/operators/operator-precedence.md
  docs/visual-basic/language-reference/statements/function-statement.md
  docs/visual-basic/language-reference/statements/select-case-statement.md
  docs/visual-basic/language-reference/statements/sub-statement.md
  docs/visual-basic/language-reference/statements/throw-statement.md
  docs/visual-basic/misc/bad-record-number.md
  docs/visual-basic/misc/bc2027.md
  docs/visual-basic/misc/bc30122.md
  docs/visual-basic/misc/bc30123.md
  docs/visual-basic/misc/bc30607.md
  docs/visual-basic/misc/bc36663.md
Labels: Accepted

#488 将英文逗号改为中文逗号
  docs/csharp/programming-guide/inside-a-program/general-structure-of-a-csharp-program.md
Labels: Accepted, Linguistic Suggestion

#490 Fix reversed translation
  docs/standard/asynchronous-programming-patterns/calling-synchronous-methods-asynchronously.md
Labels: Accepted, Linguistic Suggestion

#493 Update security-considerations-for-reflection.md
  docs/framework/reflection-and-codedom/security-considerations-for-reflection.md
Labels: In Progress

#494 fix translate is not the same
  docs/core/tools/dotnet-build.md
Labels: Accepted, Linguistic Suggestion
