Repository dotnet/docs.zh-cn, pull requests merged in 2019-08, with the labels that each got.

#425 Update index.md
  docs/core/compatibility/index.md
Labels: Accepted

#427 Update dependencies.md
  docs/core/tools/dependencies.md
Labels: Accepted, Linguistic Suggestion

#431 Update regular-expression-language-quick-reference.md
  docs/standard/base-types/regular-expression-language-quick-reference.md
Labels: Accepted

#429 Update unit-testing-best-practices.md
  docs/core/testing/unit-testing-best-practices.md
Labels: Accepted, Linguistic Suggestion

#436 Update character-classes-in-regular-expressions.md
  docs/standard/base-types/character-classes-in-regular-expressions.md
Labels: Accepted

#421 Fix some gammar and ambiguity errors
  docs/core/whats-new/dotnet-core-3-0.md
Labels: Linguistic Suggestion, Partially Accepted

#423 Update about.md
  docs/core/about.md
Labels: Accepted, Linguistic Suggestion

#424 Update dotnet-core-3-0.md
  docs/core/whats-new/dotnet-core-3-0.md
Labels: Accepted, Linguistic Suggestion

#426 Update packages.md
  docs/core/packages.md
Labels: Accepted, Linguistic Suggestion

#433 Update regular-expression-language-quick-reference.md
  docs/standard/base-types/regular-expression-language-quick-reference.md
Labels: Accepted, Linguistic Suggestion

#434 Update character-escapes-in-regular-expressions.md
  docs/standard/base-types/character-escapes-in-regular-expressions.md
Labels: Linguistic Suggestion, Partially Accepted

#451 Update backtracking-in-regular-expressions.md
  docs/standard/base-types/backtracking-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#448 Update best-practices.md
  docs/standard/base-types/best-practices.md
Labels: Accepted, Linguistic Suggestion

#438 Update grouping-constructs-in-regular-expressions.md
  docs/standard/base-types/grouping-constructs-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#441 Update quantifiers-in-regular-expressions.md
  docs/standard/base-types/quantifiers-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#444 Update substitutions-in-regular-expressions.md
  docs/standard/base-types/substitutions-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#445 Update regular-expression-options.md
  docs/standard/base-types/regular-expression-options.md
Labels: Accepted, Linguistic Suggestion

#446 Update regular-expression-options.md
  docs/standard/base-types/regular-expression-options.md
Labels: Accepted, Linguistic Suggestion

#447 Update miscellaneous-constructs-in-regular-expressions.md
  docs/standard/base-types/miscellaneous-constructs-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#442 Update backreference-constructs-in-regular-expressions.md
  docs/standard/base-types/backreference-constructs-in-regular-expressions.md
Labels: Linguistic Suggestion, Partially Accepted

#443 Update alternation-constructs-in-regular-expressions.md
  docs/standard/base-types/alternation-constructs-in-regular-expressions.md
Labels: Linguistic Suggestion, Partially Accepted

#450 Update details-of-regular-expression-behavior.md
  docs/standard/base-types/details-of-regular-expression-behavior.md
Labels: Accepted, Linguistic Suggestion

#452 Update toc.yml
  docs/standard/base-types/toc.yml
Labels: Accepted, Linguistic Suggestion

#453 Update regular-expression-example-scanning-for-hrefs.md
  docs/standard/base-types/regular-expression-example-scanning-for-hrefs.md
Labels: Accepted, Linguistic Suggestion

#456 Update backtracking-in-regular-expressions.md
  docs/standard/base-types/backtracking-in-regular-expressions.md
Labels: Accepted, Linguistic Suggestion

#439 Update grouping-constructs-in-regular-expressions.md
  docs/standard/base-types/grouping-constructs-in-regular-expressions.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#440 Update grouping-constructs-in-regular-expressions.md
  docs/standard/base-types/grouping-constructs-in-regular-expressions.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue
