Repository dotnet/docs.zh-cn, pull requests merged in 2020-05, with the labels that each got.

#575 Improve the translation
  docs/csharp/programming-guide/delegates/how-to-combine-delegates-multicast-delegates.md
Labels: Accepted, Linguistic Suggestion

#577 Fix typo
  docs/architecture/microservices/secure-net-microservices-web-applications/authorization-net-microservices-web-applications.md
Labels: Accepted, Linguistic Suggestion, P1

#578 Update reference URL in subtraction-operator.md
  docs/csharp/language-reference/operators/subtraction-operator.md
Labels: Accepted, Linguistic Suggestion, P1

#579 Update numeric-conversions.md
  docs/csharp/language-reference/builtin-types/numeric-conversions.md
Labels: Accepted, Linguistic Suggestion, P2

#586 Update lambda-expressions.md
  docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md
Labels: Accepted, Linguistic Suggestion, P1

#587 Update attributes.md
  docs/csharp/tour-of-csharp/attributes.md
Labels: Accepted, Linguistic Suggestion, P1

#588 Update async.md
  docs/csharp/async.md
Labels: Accepted, Linguistic Suggestion, P1

#590 Fix typos
  docs/standard/base-types/composite-formatting.md
Labels: Accepted, Linguistic Suggestion, P1

#593 Improve translations
  docs/csharp/programming-guide/classes-and-structs/properties.md
Labels: Accepted, Linguistic Suggestion, P1

#594 Improve translations
  docs/csharp/programming-guide/classes-and-structs/classes.md
Labels: Linguistic Suggestion, P1, Partially Accepted

#598 更新错误描述
  docs/csharp/whats-new/csharp-8.md
Labels: Accepted, P1

#600 Keep en
  docs/csharp/language-reference/keywords/reference-types.md
Labels: Accepted, Linguistic Suggestion, P1

#601 `dynamic` sample scenario update
  docs/csharp/whats-new/csharp-version-history.md
Labels: Accepted, Linguistic Suggestion, P1

#602 Fix markdown syntax error
  docs/core/distribution-packaging.md
Labels: Accepted, Linguistic Suggestion, P1
